global:
  scrape_interval: 60s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["prometheus:9090"]

  - job_name: "gatus"
    scrape_interval: 60s
    scheme: http
    static_configs:
      - targets: ["gatus:8080"]

  - job_name: "dns-a-windows"
    dns_sd_configs:
      - names:
          - "AEDC01.ae.int"
          - "AEDC02.ae.int"
          - "AEDHCP01.ae.int"
          - "AEVEEAM01.ae.int"
          - "AECERT01.ae.int"
          - "AEPROWATCH65SEC.ae.int"
          - "SANDOZPROWATCH.ae.int"
          - "SDZ-PWDATA.ae.int"
        type: A
        port: 9182

  - job_name: "dns-a-linux"
    dns_sd_configs:
      - names:
          - "AETESTSQL01.ae.int"
          - "AEDEMOSQL01.ae.int"
          - "AEMONITOR01.ae.int"
        type: A
        port: 9100

storage:
  tsdb:
    out_of_order_time_window: 30m
    retention:
      time: 30d
